name: Build Android Artifact

on:
  push:
    branches:
      - feature/secret_key

jobs:
  build:
    environment: deployment
    name: Android builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decrypt large secret
        run: ./scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Install npm dependencies
        run: |
          yarn install
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Linking
        run: ln -s ${ANDROID_HOME}/build-tools/31.0.0/d8 ${ANDROID_HOME}/build-tools/31.0.0/dx && ln -s ${ANDROID_HOME}/build-tools/31.0.0/lib/d8.jar ${ANDROID_HOME}/build-tools/31.0.0/lib/dx.jar
      - name: Build Android Release
        run: |
          cd android && ENVFILE=.env.production ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MovieTrailer
          path: android/app/build/outputs/apk/release/app-release.apk
